version: "3.6"
services:
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db/

  redis:
    image: redis
    ports:
      - 6379:6379
  
  server:
    build: src
    volumes:
     - ./src:/app
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/demo-db
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongo
      - redis
